In [1]:
import pandas as pd
train = pd.read_csv("E:/isuclasses/COMS573/lab4 materials/lab4-train.csv")
test = pd.read_csv("E:/isuclasses/COMS573/lab4 materials/lab4-test.csv")
import numpy as np
train_labels = np.array(train['Class'])
train= train.drop('Class', axis = 1)
train_list = list(train.columns)
train = np.array(train)
test_labels = np.array(test['Class'])
test= test.drop('Class', axis = 1)
test = np.array(test)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, AdaBoostClassifier
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.neural_network import MLPClassifier
from sklearn import preprocessing, metrics
from sklearn.metrics import confusion_matrix

In [25]:
from sklearn.preprocessing import StandardScaler 
scaler =  StandardScaler()  
scaler.fit(train)
train = scaler.transform(train)  
test = scaler.transform(test)


clf1 = LogisticRegression(solver='lbfgs', multi_class='multinomial', random_state=1)
clf2 = GaussianNB()
clf3 = KNeighborsClassifier(n_neighbors=20) 
clf4 = tree.DecisionTreeClassifier()
clf5 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf6 = RandomForestClassifier(n_estimators = 10, random_state = 10)
clf7 = AdaBoostClassifier(n_estimators = 10, random_state = 10)

eclf1 = VotingClassifier(estimators=[('lr', clf1), ('gnb', clf2), ('knn', clf3), ('dt', clf4), ('nn', clf5)], voting='hard')
eclf1.fit(train, train_labels)
prediction = eclf1.predict(test)
print(confusion_matrix(test_labels, prediction))
print(eclf1.score(test, test_labels))

[[230   8]
 [ 45  18]]
0.8239202657807309


In [24]:
eclf2 = VotingClassifier(estimators=[('lr', clf1), ('gnb', clf2), ('knn', clf3), ('dt', clf4), ('nn', clf5)], 
                         voting='soft', weights=[4, 2, 4, 1, 4], flatten_transform=True)
eclf2.fit(train, train_labels)
prediction = eclf2.predict(test)
print(confusion_matrix(test_labels, prediction))
print(eclf2.score(test, test_labels))

[[230   8]
 [ 42  21]]
0.8338870431893688


In [28]:
eclf3 = VotingClassifier(estimators=[('lr', clf1), ('gnb', clf2), ('knn', clf3), ('dt', clf4), ('nn', clf5), 
                                     ('rf', clf6), ('ab', clf7)], voting='hard')
eclf3.fit(train, train_labels)
prediction = eclf3.predict(test)
print(confusion_matrix(test_labels, prediction))
print(eclf3.score(test, test_labels))

[[230   8]
 [ 48  15]]
0.813953488372093


In [45]:
eclf4 = VotingClassifier(estimators=[('lr', clf1), ('gnb', clf2), ('knn', clf3), ('dt', clf4), ('nn', clf5), 
                                     ('rf', clf6), ('ab', clf7)], voting='soft', weights=[8, 1, 16, 1, 12, 1, 4], 
                         flatten_transform=True)
eclf4.fit(train, train_labels)
prediction = eclf4.predict(test)
print(confusion_matrix(test_labels, prediction))
print(eclf4.score(test, test_labels))

[[229   9]
 [ 39  24]]
0.840531561461794
