In [1]:
import keras


Using TensorFlow backend.


In [96]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation, Convolution2D, MaxPooling2D, Flatten, Dropout
from keras.utils import np_utils
from keras.optimizers import Adam
from sklearn import preprocessing, metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [100]:
opt_train = pd.read_csv('E:/isuclasses/COMS573/lab3/UCI/optdigits.tra.txt', header=None).rename(columns={64: 'class'}).values
opt_test = pd.read_csv('E:/isuclasses/COMS573/lab3/UCI/optdigits.tes.txt', header=None).rename(columns={64: 'class'}).values

In [123]:
train_x = train[:, :64]/255.0
test_x = test[:, :64]/255.0

train_y = train[:, 64]
test_y = test[:, 64]

lb = preprocessing.LabelBinarizer()
train_y = lb.fit_transform(train_y)
test_y = lb.fit_transform(test_y)

In [165]:
model = Sequential([
    Dense(10, input_dim = 64),
    Activation('relu'),
    Dense(50),
    Activation('relu'),
    Dense(25),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])

model.summary()

sgd = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.95, nesterov=True)
model.compile(
    optimizer = sgd,
    loss = 'categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(train_x, train_y, epochs = 50, validation_split=0.2)
prediction = model.predict_classes(train_x)
cm = confusion_matrix(train_y.argmax(axis=1), prediction)
print(cm)
print(classification_report(train_y.argmax(axis=1), prediction))


loss, accuracy = model.evaluate(test_x, test_y)
print('test loss:', loss)
print('test accuracy:', accuracy)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_220 (Dense)            (None, 10)                650       
_________________________________________________________________
activation_209 (Activation)  (None, 10)                0         
_________________________________________________________________
dense_221 (Dense)            (None, 50)                550       
_________________________________________________________________
activation_210 (Activation)  (None, 50)                0         
_________________________________________________________________
dense_222 (Dense)            (None, 25)                1275      
_________________________________________________________________
activation_211 (Activation)  (None, 25)                0         
_________________________________________________________________
dense_223 (Dense)            (None, 10)                260       
__________

[[364   0   2   0   1   4   0   0   1   4]
 [  0 368   0   3   1   0   0   0  11   6]
 [  1   3 363   9   0   0   0   0   4   0]
 [  0   1   0 379   0   4   0   0   0   5]
 [  1   2   0   0 372   0   3   0   1   8]
 [  0   0   0   1   0 370   0   0   0   5]
 [  3   5   1   0   1   0 363   0   4   0]
 [  0   0   0   5   0   3   0 364   0  15]
 [  0   1   2   1   0   1   0   0 369   6]
 [  0   0   0   7   1   1   0   0   0 373]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       376
           1       0.97      0.95      0.96       389
           2       0.99      0.96      0.97       380
           3       0.94      0.97      0.95       389
           4       0.99      0.96      0.98       387
           5       0.97      0.98      0.97       376
           6       0.99      0.96      0.98       377
           7       1.00      0.94      0.97       387
           8       0.95      0.97      0.96       380
           9       0.88     

In [166]:
train = pd.read_csv('E:/isuclasses/COMS573/lab3/UCI/optdigits.tra.txt', header=None).rename(columns={64: 'class'}).values
test = pd.read_csv('E:/isuclasses/COMS573/lab3/UCI/optdigits.tes.txt', header=None).rename(columns={64: 'class'}).values

train_x = train[:, :64].reshape(train.shape[0], 8, 8, 1)/255.0
test_x = test[:, :64].reshape(test.shape[0], 8, 8, 1)/255.0

train_y = train[:, 64]
test_y = test[:, 64]

lb = preprocessing.LabelBinarizer()
train_y = lb.fit_transform(train_y)
test_y = lb.fit_transform(test_y)

In [177]:
model1 = Sequential()
model1.add(Convolution2D(
    input_shape = (8, 8, 1),
    filters = 32,
    kernel_size = 7,
    strides = 1,
    padding = 'same',
    activation= 'relu' 
))
model1.add(MaxPooling2D(
    pool_size=2,
    strides = 2,
    padding = 'same'
))

model1.add(Convolution2D(
    filters = 64,
    kernel_size = 7,
    strides = 1,
    padding = 'same',
    activation= 'relu'
))
model1.add(MaxPooling2D(2, 2, 'same'))

model1.add(Flatten())
model1.add(Dense(128, activation= 'relu' ))
model1.add(Dropout(0.5))
model1.add(Dense(10, activation= 'softmax' ))

adam = Adam(lr=0.0001)
model1.compile(loss= 'categorical_crossentropy' , optimizer= adam , metrics=[ 'accuracy' ])
model1.fit(train_x, train_y, epochs = 50, validation_split=0.2)

prediction1 = model1.predict_classes(train_x)
cm1 = confusion_matrix(train_y.argmax(axis=1), prediction1)
print(cm1)
print(classification_report(train_y.argmax(axis=1), prediction1))

loss, accuracy = model1.evaluate(test_x, test_y)
print('test loss:', loss)
print('test accuracy:', accuracy)

Train on 3058 samples, validate on 765 samples
Epoch 1/50
3058/3058 [==============================] - 4s 1ms/step - loss: 2.2946 - acc: 0.2767 - val_loss: 2.2836 - val_acc: 0.5425
Epoch 2/50
3058/3058 [==============================] - 1s 385us/step - loss: 2.2617 - acc: 0.4235 - val_loss: 2.2305 - val_acc: 0.5438
Epoch 3/50
3058/3058 [==============================] - 1s 372us/step - loss: 2.1748 - acc: 0.4372 - val_loss: 2.0970 - val_acc: 0.5595
Epoch 4/50
3058/3058 [==============================] - 1s 388us/step - loss: 1.9896 - acc: 0.4892 - val_loss: 1.8486 - val_acc: 0.5686
Epoch 5/50
3058/3058 [==============================] - 1s 375us/step - loss: 1.7217 - acc: 0.5585 - val_loss: 1.5392 - val_acc: 0.7176
Epoch 6/50
3058/3058 [==============================] - 1s 378us/step - loss: 1.4601 - acc: 0.5988 - val_loss: 1.2589 - val_acc: 0.7804
Epoch 7/50
3058/3058 [==============================] - 1s 375us/step - loss: 1.2428 - acc: 0.6504 - val_loss: 1.0507 - val_acc: 0.7804
Epo